spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ferias_db
spring.datasource.username=postgres
spring.datasource.password=theuzin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080